name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Building library
        run: |
          npm install
          npm run build

      - name: Building sandbox
        run: |
          cd sandbox
          npm install
          npm run build
